### ISSUE TITLE
UX: Lock Up Feature Exploration

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-treasury-dashboard#105]
# Background
Our Treasury Dashboard currently displays liquid NEAR tokens and those reserved for hosting fees. However, we need to represent another token state: tokens from locked-up accounts (e.g. account.lockup.near), which may represent grants with certain restrictions. These locked tokens can be staked and unstated, but their availability for transfer depends on the specific conditions of the lockup.

# UX Need
We need a way to represent and manage locked tokens within the Treasury Dashboard. This includes: 
- **Display lock-up account information:** Show relevant details like total balance, owner's balance, locked up amount, liquid amount, and staking report. 
- **Enable staking and unstaking:** Allow users with "create" permission to initiate staking/unstaking requests for locked tokens, even if they are not yet available for transfer. And track the status of those requests and allow users with "vote" permissions to approve/reject them.
- **Allow transfer of available tokens:** Provide a way for users to create transfer requests for available tokens from the lock-up account to the main SputnikDAO account. Allow users with "vote" permissions to approve/reject requests related to locked tokens.

# Acceptance Criteria
- [x] Create mockups and user flows demonstrating the proposed UX solutions for:
  - [x] Displaying lock-up account information within the Treasury Dashboard.
  - [x] Staking and unstaking locked tokens.
  - [x] Transferring available tokens from the lock-up account.
- [x] Identify and document potential edge cases and error handling scenarios.
- [x] Present the proposed solutions and gather feedback from portal dev team
- [x] Create follow up development tasks on the finalized approach 

# Additional Details

## How lock-up grants work:
- Organizations can create lock-up grants with parameters such as the recipient owner (e.g. DAO's treasury account), total amount, duration (lock-up period), cliff (time before tokens become available), and grant creator account.
- When a grant is created, a dedicate lock-up account (e.g. name.lockup.near) is generated to hold the locked tokens. This account has attributes like total balance, owner's balance (available tokens), locked up amount, liquid amount, and staking report.
- NEAR tokens can be liquid (available for transfer) or locked up with specific unlocking conditions.
- The recipient owner can stake and unstake locked tokens even before they become liquid. Once unlocked, they can transfer them (e.g. to their main SputnikDAO account or elsewhere).
  
## Considerations
 * **Lock-up account details**: Determine the most important information to display and how to present it clearly.
 * **Staking and unstaking**:  Ensure a seamless user experience for staking and unstaking locked tokens, similar to the existing "Stake Delegation" feature.
 * **Transfer functionality**:  Design a clear and intuitive flow for transferring available tokens.
 * **Error handling and edge cases**:  Consider scenarios like insufficient balance, exceeding staking limits, and handling unlocking conditions.
 * **Future integration**:  Keep in mind the future implementation of creating lock-up grants directly within the Treasury Dashboard.

**Comment by FREZZZBE** [comment]
@ori-near @Megha-Dev-19 


Here is lockup staking flow if you dont have staked lockep yet (ignore this on the video)
https://github.com/user-attachments/assets/cae430a1-3304-472c-844a-bcb6362ab0e3


if you have some staked lockup amount. You cannot select other validator
![Image](https://github.com/user-attachments/assets/ded0d22c-8738-4f87-8c76-f575d159cbc9)

**Comment by ori-near** [comment]
Thank you @FREZZZBE – let us know if you're looking for specific feedback or have any questions for us. Or if your message is just an FYI.
