### ISSUE TITLE
UX: Need UI for Delete Request Flow

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-treasury-dashboard#109]
# Background
See https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/issues/75 for more context.

# Acceptance Criteria
- [x] Create UI flow that shows:
  - [x] Add a delete column and button on the right side that only users with "Create" permission can see.
  - [x] When a user clicks on the Delete button, they should see a warning screen to confirm
  - [x] When a request is deleted, show it under history with "Deleted" status
- [x] When this ticket is done, remove "Has Dependency" label from https://github.com/orgs/NEAR-DevHub/projects/4/views/20?pane=issue&itemId=83698312&issue=NEAR-DevHub%7Cneardevhub-treasury-dashboard%7C75 and link the design in that dev task

**Comment by FREZZZBE** [comment]
@FREZZZBE @ori-near 

https://www.figma.com/proto/hNg69dceqgi7yMYtovrbYc/%F0%9F%8F%A6-Multisig-Treasury-Application?page-id=4202%3A18821&node-id=534-4696&node-type=frame&viewport=175%2C-361%2C0.29&t=9Hre5OwjwIYcthfV-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=534%3A4696

**Comment by ori-near** [comment]
@FREZZZBE looks great, thanks so much! BTW – do you think it matters if we show in history who completed the delete request?

**Comment by FREZZZBE** [comment]
@ori-near I dont relly want to create additional column just for this cornercase. But to have this information also resonable but only if it has possibility to delete for not same person as creator

here an idea! [Prototype](https://www.figma.com/proto/hNg69dceqgi7yMYtovrbYc/%F0%9F%8F%A6-Multisig-Treasury-Application?page-id=4202%3A18821&node-id=534-4696&node-type=frame&viewport=175%2C-361%2C0.29&t=9Hre5OwjwIYcthfV-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=534%3A4696)


![Image](https://github.com/user-attachments/assets/782dc9db-c40a-4bbd-8ff4-fc3ea0487e51)

**Comment by ori-near** [comment]
Great solution! Considering this ticket complete. Thank you, @FREZZZBE!
