### ISSUE TITLE
Dev: Setup Templar with Treasury & Portal instance

### ISSUE THREAD

**Issue by Megha-Dev-19** [NEAR-DevHub/neardevhub-treasury-dashboard#122]
AC
- [x] Treasury
- [x] Portal

**Comment by Megha-Dev-19** [comment]
I have shared the link for the [treasury dashboard](https://near.social/treasury-templar.near/widget/app?page=dashboard)
For portal, we still need to fix the bugs with the indexer, will update the status here once it's done
cc: @ori-near

**Comment by ori-near** [comment]
Waiting for @Tguntenaar to complete Indexer epic.
