### ISSUE TITLE
UX: Redesign Transactions at Dashboard

### ISSUE THREAD

**Issue by FREZZZBE** [NEAR-DevHub/neardevhub-treasury-dashboard#131]
### Problem: 
The current table is not scalable and doesn't fit multiple wallet treasuries.

### User story
As a user, 
I want to see from what wallet this transaction was made and what the destination wallet 
so than I will clearly see what treasury wallet was used and more. 

![Image](https://github.com/user-attachments/assets/afaf4959-b7c3-4563-820b-383c003ab89c)

**Comment by Megha-Dev-19** [comment]
@FREZZZBE how do we segregate the lockup and sputnik dao transactions?

**Comment by FREZZZBE** [comment]
@Megha-Dev-19  you can see it in from/to columns. If the wallet end with .lockup.near that means lockup wallet was used to send or receive some funds.

**Comment by Megha-Dev-19** [comment]
oh sorry yes we have both, so one of them will have it, looks good to me.
