### ISSUE TITLE
Upgrade near-linkdrop contract to support contract deployment

### ISSUE THREAD

**Issue by frol** [NEAR-DevHub/neardevhub-treasury-dashboard#144]
### Background

We need to merge and deploy https://github.com/near/near-linkdrop/pull/28, so our "factory" can create new account and deploy web4 contract to it

### User Story

As part of the self-onboarding flow, I want it to create a new account with web4 URL available for me to use my treasury management UI from my custom domain

### Acceptance Criteria

Self-onboarding contract should be able to create a second-level account and deploy a web4 contract to it

### Priority

🟠 P1 : High

**Comment by petersalomonsen** [comment]
I see that https://github.com/near/near-linkdrop/pull/28 is merged now, but it does not seem to be deployed? When will it be deployed?
