### ISSUE TITLE
Settings - Pending Requests Title

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-treasury-dashboard#177]
# Current State
Currently a settings pending request just has "update policy" title:
<img width="1669" alt="Image" src="https://github.com/user-attachments/assets/181d9a20-3fd5-476a-856e-cba6493d65cd" />

However, this is not entirely clear to the user what that means. If the user clicks Details, they see a super long list of changes, which are overwhelming to parse through & not very human readable:
<img width="588" alt="Image" src="https://github.com/user-attachments/assets/eeabb2cb-c3e9-4594-8562-4b500d1bdd16" />

This creates a problem for approvers not knowing what request needs to be approved.

# Desired State
Is there a way for us to create a more user friendly set of templates for common changes? For example, in this case I changed the policy to increase Voting Duration from 1 to 2.

**Comment by Megha-Dev-19** [comment]
hey @ori-near 
That's a good point, we can edit the title as we want since that’s set by us
So if you have preference for title for all three kinds of request (duration, threshold, members)let me know, I will make the update.

**Comment by ori-near** [comment]
Hi @Megha-Dev-19 as we discussed yesterday, let's update the Title column to include the affected area (e.g. "Update Policy – Members Permissions", "Update Policy – Voting Thresholds") etc and just use whatever we call the page in the settings navigation menu to represent the area. 

Within the actual details popup, we could have two sections:

# Summary
@user requested to increase voting from x to y 

# Transaction Details
Include the existing black section 

Let me know if you have any questions!
