### ISSUE TITLE
Treasury – Operations Page, Sub-Navigation, and Payments Section Setup

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-treasury-dashboard#18]
# Background
This ticket focuses on setting up the main structure of the "Operations" page, including the sub-navigation and the layout of the "Payments" section. The functionalities of each specific section within "Payments" ([Pending Requests](https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/issues/19), [History](https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/issues/21), [Payment Recipients](https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/issues/22)) will be addressed in subsequent tickets, along with their respective permissions.

# User Stories
- As a regular user, I want to access the Treasury "Operations" page and view the payment history to understand the financial activities of DevDAO.
- As an admin with approve permissions, I want to access the "Operations" page and manage pending payment requests to control outgoing payments.
- As an admin with create permissions, I want to access the "Operations" page and manage payment requests and recipients to initiate and track payments.

# Acceptance Criteria 
- Add an "Operations" link to the Treasury dashboard navigation.
- Clicking the "Operations" link displays a page with a sub-navigation bar containing:
  - Payments
  - Stake Delegation
  - Asset Exchange
- The initial view on the "Operations" page shows the ["Payments: Pending Requests"](https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/issues/19) page
- The Payments Section has a sidebar with three link:
  - [Pending Requests](https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/issues/19)
  - [History](https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/issues/21)
  - [Payment Recipients](https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/issues/22)
- Permissions for each page/functionality:
   - All users can view "[Pending Requests](https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/issues/19)," "[History](https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/issues/21)," and "[Payment Recipients,](https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/issues/22)" but cannot create or edit requests/recipients.
   - Admins with create permissions can view and manage all pages and functionalities within "Payments."

# Attachment

![Payments - Pending Requests](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/7dd61c5c-d846-4f70-a5ef-efe8ffe6d2b1)

**Comment by Megha-Dev-19** [comment]
It's completed
