### ISSUE TITLE
Create recipient

### ISSUE THREAD

**Issue by petersalomonsen** [NEAR-DevHub/neardevhub-treasury-dashboard#5]
**User story**

As a moderator
I need a form for registering a recipient
So that I can add a receiver of proposal grants to the list of known recipients

**Acceptance criterias**

- Verify that only moderators can access the UI and transactional contract methods
- Verify that the recipients are stored on the contract for the sponsoring DAO

**Overall acceptance criterias ( applies to each user story )**

- Verify that the UI implementation corresponds to the Figma design
- Verify frontend automatic tests
    - Verify that there's an automatic playwright test visualized in an automatically generated screen recording
    - Verify that the tests covers relevant usage and misuse scenarios
    - Verify that the tests demonstrates how the UI is guiding the user in an intuitive way by providing validation messages and hints
- Verify backend
    - Verify that the contract implements the data structure that represents the frontend
    - Verify that the contract implements the same verification mechanisms and validation messages as the frontend
- Verify backend automatic tests
    - Verify that there are unit test on the detailed level covering multiple variants of input and expectations
    - Verify that there are integration tests using near-workspaces-rs for covering the scenarios of input and expected output from the frontend
    - Verify that the playwright tests interacts with a testnet contract, to show the full end-to-end flow
- Before merge: Verify that the functionality, test coverage (as shown by the screen recording), is according to expectations of the product owner.

**Comment by Megha-Dev-19** [comment]
we don't have a UI for it yet neither we plan to do it anytime soon, so I m closing it for now.
