### ISSUE TITLE
Dev: Self Create Flow Contract

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-treasury-dashboard#89]
## Problem

Self Create flow should end up with the user signing, ideally, a single transaction. We will need a helper contract (the self create flow contract) so user signs this one transaction and we do the rest through cross-contract calls.

## Solution 

Is a helper contract that does these 4 steps in a single tx. The transaction should accomplish the following:

1. Deploy a DAO.
Create and configure a new Sputnik DAO subaccount using the Sputnik factory [create](https://github.com/near-daos/sputnik-dao-contract/blob/3d568f9517a8c7a6510786d978bb25b180501841/sputnikdao-factory2/src/lib.rs#L100) method. The create method on contract `sputnik-dao.near` should be used for this. It costs between 5 and 6 Near to deploy a DAO. The DAO contract will be a sub account of `sputnik-dao.near`. For example `new-treasury.sputnik-dao.near`.

2. Create a new account, for example `new-treasury.near`
This new account can be used to deploy the front end on but in order to store the components it needs a storage deposit. As a callback for making this new account we can do step 3.
 	
3. Pay for SocialDB storage + deploy BOS components
 These interactions are with the [social-db contract](https://github.com/NearSocial/social-db/blob/b4a023d234d0f24a2cf0d4b7998ea485f90f576e/contract/src/api.rs#L147)

4. On this new account we can deploy the web4 contract that is defined [here](https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/blob/5e18248872caed22e50d980d0156d8146c5efc97/web4/treasury-web4/src/lib.rs#L39) with BOS gateway.
Checkout [web4](https://web4.near.page/) for more info.

**Comment by Tguntenaar** [comment]
The web4 contract is stored in the treasury dashboard repository [here](https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/blob/5e18248872caed22e50d980d0156d8146c5efc97/web4/treasury-web4/src/lib.rs#L39)

**Comment by ori-near** [comment]
Moving this to sprint 3 and assigned to @petersalomonsen

**Comment by petersalomonsen** [comment]
Depends on https://github.com/near/near-linkdrop/pull/28 to be merged

**Comment by petersalomonsen** [comment]
Tested again after https://github.com/near/near-linkdrop/pull/28 is merged, but does not seem to be deployed. It needs to be deployed to proceed here.

**Comment by frol** [comment]
@petersalomonsen It is now deployed: https://nearblocks.io/txns/e6DFrDNbJp2zb8BCBvwfPKR2G896sUV2ZEha8yputAv

**Comment by ori-near** [comment]
Thank you @frol!

**Comment by petersalomonsen** [comment]
> [@petersalomonsen](https://github.com/petersalomonsen) It is now deployed: https://nearblocks.io/txns/e6DFrDNbJp2zb8BCBvwfPKR2G896sUV2ZEha8yputAv

Thanks @frol ! Works in the tests, and should now be ready for review!

**Comment by ori-near** [comment]
@frol can you please review this?
